server:
  port: 8080


spring:
  data:
    redis:
      client-type: lettuce
      #     单机模式
      host: 127.0.0.1
      port: 6379
      password: 123456
      #     哨兵模式
      sentinel:
        master: mymaster
        nodes: 127.0.0.1:6379
      #     集群模式
      cluster:
        nodes: 127.0.0.1:6379
      lettuce:
        pool:
          # 最大活动连接数
          max-active: 8
          # 最大空闲连接数
          max-idle: 8
          # 最小空闲连接数
          min-idle: 0
          # 当连接耗尽时，最大等待时间。负值表示没有限制