server:
  port: 8080


spring:
  data:
    redis:
      client-type: lettuce
      lettuce:
        cluster:
          nodes: 127.0.0.1:6379
        pool:
          # 最大活动连接数
          max-active: 8
          # 最大空闲连接数
          max-idle: 8
          # 最小空闲连接数
          min-idle: 0
          # 当连接耗尽时，最大等待时间。负值表示没有限制